### PR TITLE
save feature implementation done

### PR DESCRIPTION
**Pull request by obrito00**
completed the post request function create_movie() in app.py
completed the create_movies_form.html
completed test_create_movies_page.py that tests the create_movie() function

### CODE REVIEW

**Comment by HaydenCJuneau** [comment]
Looks good, however we need to validate the data sent by the form in the backend as well. If you go into inspect element and remove the 'required' tags from the inputs, you can submit empty data and it shows up empty in the table. 
image

**Comment by HaydenCJuneau** [comment]
Also, make sure you write unit tests for this feature in `tests/unit/test_create_movie.py`

**Comment by obrito00** [comment]
i updated the create_movie() for backend validation and wrote unit tests for them

**Comment by HaydenCJuneau** [comment]
Hi, looks like the tests in `tests/unit/test_create_movie.py` still needs to be created. 
image

**Comment by obrito00** [comment]
so this time i finally added the unit tests

**Review by HaydenCJuneau — APPROVED** [review]
Tests are passing, all needed todos have been completed, feature looks good. Approving.

**Pull request merged**
